spring:
  datasource:
    url: jdbc:mysql://81.69.99.56:3306/feiyu?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
  main:
    allow-bean-definition-overriding: true
  application:
    name: feiyu-web
  cloud:
    nacos:
      config:
        # 配置文件的环境
        group: ${spring.profiles.active}
        # 配置文件的格式
        file-extension: yaml
        # 配置中心的地址
        server-addr: 81.69.99.56:8848
        # 配置文件prefix
        prefix: ${spring.application.name}
        #命名空间
        namespace: mall
  mail:
    host: smtp.163.com
    username: dpyuyu@163.com
    password: DXBGKYUQDUNZSXJT
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
netty:
  port: 7008